# -*- coding: utf-8 -*-
"""Group 42 PLP hackathon

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-tXA1Qm_10BYSPpp2lA09DEMtpuf22f3

**Bus Fare Challenge – Day 1 Task one**
"""

from datetime import date

today = date.today()
print("Date:", today)

import datetime
today = datetime.datetime.today()
print(today.strftime("Day:%A"))

import datetime
today = datetime.datetime.today()
print(today.strftime("Day:%A"))

if today: ("Saturday")
print("Fare: 60")

"""**Sales Tax Challenge – Day 1 task 2**"""

def main():

    # Ask for the wall square to be painted.
    wall_square = input('Enter the number of square feet to be painted: ')
    
    # Ask for the paint price per gallon.
    price_gallon = input('Enter the paint price per gallon: ')

    estimate(wall_square, price_gallon)

def estimate(wall_square, price_gallon):
    # 115 sq ft = 1 gallon + 8 hrs of labor (labor is $20 per hour)
    num_gallons = wall_square/115
    hours_labor = num_gallons * 8
    total_price_gallon = num_gallons * price_gallon
    total_labor = hours_labor * 20
    final_total = total_price_gallon + total_labor
    print ('The total estimated price for this paint job is $', final_total)

# Call the main function.
main()

"""**Personality test program - Day 2 Task one**

"""

num = int(input("Please enter number of books: "))

points= 0
if num==1:
  points= 6*num
elif num==2:
    points= 16*num
elif num==3:
      points= 32*num
elif num>=4:
        points= 60*num
        print(f"points:{points}")

"""**Challenge - Day 2 Task 2**"""

career_list= ['doctor', 'engineer', 'lawyer']
career_advices= ['have an A', 'have an A-', 'have a B+']
career_queries= ['what grade did you get?']
#user grade
grade=int(input("Enter grade"))

if grade>=100:
 print('This is an A!youre qualified to be a doctor!')
elif grade==90 or grade<99:
 print('This is an A-! youre qualified to be an engineer!')
elif grade==70 or grade<79:
 print('This is a B+! youre qualified to be a lawyer')
else:
 print("Error, input invalid")
exit()

"""**Door lock system Challenge – Day 3 Task 1**"""

# Door lock system

import datetime 

current_time = datetime.datetime.now() 


put_password = input('Please put your password: ')
print('You have put your password correctly...')
print()

open = 'open'
close = 'close'
quit = 'quit'

while True:
    password = input('Enter your password: ')
    if password == put_password:
        print('Password entered correctly...')
        break
    else:
        print('Incorrect password. Try again.')
        continue


while True:
    open = False
    close = False
    quit = False

    cmd_1 = input('Enter your command: ')
    print()

    if cmd_1 == 'open':       
        print('The door is now open') 
        print('Door last open at ',current_time)
        time_now = datetime.datetime.now()
        open = True
        break

    elif cmd_1 == 'close':
        close = True
        print('The door is now closed')
        print('Door last closed at ',current_time)
        time_now = datetime.datetime.now()
        break

    elif cmd_1 == 'quit':
        quit = True
        break

    else:
        print('Invalid input')
        break


while True:
    if quit == True:
        print('You have logged out')
        break

    cmd_2  = input('Enter your command: ')
    print()

    if close == True and cmd_2 == 'close':
        print('The door is already locked')
        print('Door last closed at ',time_now)
        continue
        
    if cmd_2 == 'open' and open == True:       
        print('The door is already open')  
        print('Door last open  at ',time_now)
        continue

    if cmd_2 == 'close':
        print('The door is now closed')
        print('Door last closed at ',time_now)
        close = True
        continue

    elif cmd_2 == 'open':
        print('The door is now open')
        print('Door last open at ',time_now)
        continue
        open = True

    if cmd_2 == 'quit':
        print('You have logged out')
        break

    else:
        print('Invalid input')
        continue

"""**Day 3: Challenge Day 3 task 2**"""

def main():

    # Ask for the number of fat grams.
    fat_grams = input('Enter the number of fat grams consumed: ')
    fat_calories(fat_grams)

    # Ask for the number of carb grams.
    carb_grams = input('Enter the number of carbohydrate grams consumed: ')
    carb_calories(carb_grams)

def fat_calories(fat_grams):
    # Calculate the calories from fat.
    # calories_from_fat = fat_grams*9
    calories_from_fat = fat_grams * 9
    print ('The calories from fat are', calories_from_fat)

def carb_calories(carb_grams):
    # Calculate the calories from carbs.
    # calories_from_carbs = carb_grams * 4
    calories_from_carbs = carb_grams * 4
    print ('The calories from carbohydrates are', calories_from_carbs)

# Call the main function.
main()